spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120

wx:
  appId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  notifyUrl: http://imooc-mall.natapp1.cc/pay/notify
  returnUrl: http://127.0.0.1
#alipay:
#  appId: 2018062960540016
#  privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCC/tk1oqymli5HpP9MxOkNofKkON1a6EqKg/S0++mZoKLInLasLkNuz0F8nSg/nBZGMv8XcIOXeOsK1ZT9tibxlgzun22lnBpHLueCAZlqITx33XO8SwiVULar2NIVFJwuUdvHPf/2Wj361cTd+zw+uJTPy3vIBljeOHDajzqBg9m5JrCIOgUze+4MZBT5/74gwwwpMDhRHRfR+4FTFmxqqzbTBGaFv4gCLSRB/3VpuruAP5AKCTR2ATHXgFO9veCemNwx5sI3F9Tw43+16xzAZh2T/6Xb3d31H9k31h9Iai7t2s00qY6eKsFpdi4ySK5qB2G9lbFvbpBv+3gz/5UFAgMBAAECggEANWn7Yc5yPf8w4c/atg/4w7FMgkAZqm7brj1+M6ogp58DoW+dYPoATxe9qTVf6wgXYQp8T692SPZqSOGsPgPfP1Ui8s4ZZJURdgMfLTi/uLHSuUGYZqfl2RSvV8UybJwZzx1b05NpYqeLbFNsUeOWvjB/pXdggsBrzjkPc19ByPtERzjiEFzvxGdYPDdvgNUmvbQj647X8umdyDAcNAbd8rkSQW87zBT12OQ/i/QR74BBg4VBJqTg9APk9mdVNufvxMwi9+lyGsGRFdnjmPCLHJvnT3Nh9KSHWuLrOeUjkGVEozd40iz/8LVwr+BZNeL6EjtZ3ztfphnIl92lMFNhQQKBgQDlm0t5N0REM0al/L0BygkwLsHHvAmjYhzjDJeooLgH0NyYYP/ruqqF6oPxDDaw17pciEypyOdoQ1JFaw9Uq41PfZlqL74PehSD3KWe7pPzlWIukaDq1aPit/pox92+ZO0lqwHQa80Tf1PO55xAVJQPltrhScnAmZiVIG1TD9z+sQKBgQCSDbGW2lVx5b9s1R0l8SRvoHQc83iIIyqx/+UJEEwxEMwSJ4ygAfUPcrJOYs2gOB9Ny08xqtNEQKlghwgwFqIec705AiU67Bw3TjWHnxgzvhzLPCrty/yJbWMmpXDjMm/VvwASkBL6pijjh/GUrRsJvh0McgWkDIg8OgIRu5rYlQKBgQChJ+nGb7sTn2XT9Vv4GIVwczEB7wJY0fFyj5EXA4+HtNpQfazDGOa9TchD9Q2h/BjK/8PHW8LIVJA3NxiwliR+CasXc+ET3dzuXH1G2y+vRUd/ZimrCj6YUAeLadVC4HXu/WMtlayAJdt+GuR55qNxebGxdOgNrgEBkpwJM9YqUQKBgCvFcNit/HeTDEiYohCx8WKG6uWWTiQ2reAEueZ6fOsjhpVWRv3ZOFF15Vw6njeLOk59RPG0qXZGDr0AGwMWdWW8+BOyweejxV0J0l8f3gf7zPNXx+HWhYvGPbXiVS+x+PRNNr9ZcGawD4cJQex16KmF0XzeWzRsERRDqkUYPXL1AoGBAJVzao5Irdt0wj/R8NG3uVeEMbESNLKNLZ7M9hPaZn2xacoPHXXLKg2m546RYNOngYLB5l9dbpake5BoXtuGylmtD1tZvGSxLmznfrxQpZr0vuR2iCIgsVGdPhJlIRbKyeocofsRdaXgD413O4MCi/WmJ4E1ydyOqv+2cCQQAJBB"
#  publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtojdtkETo4OEsQLeyyPwtWK9ZqYJANq6jjXC74vk9n/r88yW577y7VdxcK9X/F/wvR7D8of7lndYdhg6xZro0eO2skPZTU+A549J7tfzahVbIBAS+x1WPFJwPtVrfBBvkwHL8PT+YnMcxKyBxOa6wo8fzJs1NgU1+qnDCpwUFyv59GUfdzBvTPL1fY3ZzvRHFHbapevVltbO/jNV0thb8dafmcJXl8lnjQy3XlH3eTH28tlVfqickacfRl/WSD8WN3dGgF7dTDKYfSR7YB7jsHe6VzoHM3UnD9/yQbi/Z3ZrL7yOxEjq4tfrKlZIW7ZCoUpOU4QdPIRhLeC6nWyGrQIDAQAB"
#  notifyUrl: http://127.0.0.1:8081/pay/notify
#  returnUrl: http://127.0.0.1:8081/#/order/list
alipay:
  appId: "2021000117647234"
  privateKey: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCtf5Iod9TRUN/sAqzTUNtCsE/6hNFbuoBBQJw6JAReyDEgMe/d/YqhaMmpGx1QmxZrNvai90Rm9emYzkbwaLumvBSHy3927f8e91kRiFghE+y/khB3EUov8G/rHJjanDWgmsrcBSfuchB+C17Ps5uGRp45piPy80KABbWuAikQmbGhwXcz0i9ZcjgklUygFrdzE2hVjAuiuPdSn2G+Ciit+kYdv1rfpz0Vksk7TGXxK8cpzfOmi8L7mbIvb84/PSUsVw/J49GbRtGMk9vl0zEwpn+xQbeXHqab6WD2MbC8lfpD8jH+MK5mozOPcki4xgAtMoUeUV4GsLdOZXlnceEZAgMBAAECggEBAI/rbvaa0LMBf35riamRPRDI6M9LNc/9mT6HthCUp/tn3ThztCJVm5XhMsdQcrTWsXYmldkBfIBcJXZYRohOmLrq8azjpcymCCdLz1q320M1IAKZy4a5lOzHak+B3VoaknGzdeula0Zk4EFudSueNbjhA4eWxeNW3ycLlXXO3Pmi5jxXVCx/BxFNTMQ0Er3Xa1WfKXMoUX44oUri88xStMKR4thUI9pMVIGgZDPFP4WdckJPuylBNtodfTCmMXiW/J1l1riT+RituLm2ZV7EX1FuBw35DUtoUYifpVNrXhbUa2YAl7g1C1zoOFAPXiIB6H5y7/ptpDR1+Hne16CJj/ECgYEA4aekhXXGedtDjoK4CHHdNMrrCFqUyan/OA1eC8NpCl6Iv7k0xhVhFXZXrk65NPZM8Rwcixqju/5xaHD2JKpl7KCZXKrRAXakBpVAmyn9Zzs8ul1FPlV6aYKzvooI9HxBakuK++Mhnn4PSYcSWnYMdbjucNwKkF+7nJJEYHPkVZMCgYEAxNRlYpbyK13zwLMFHANhpPPKk3eOwKaIvPmNXTcoDerAqsrTWAOECWGJ7Nm7bafzKSi2maW1vBTQU8YICKIxei//h+tH2OrovjxTWfMcTRFIuu470pMUr2QO5gKsni2/CCHvw6K2SkWl/bI4a9pCmT0d5+5uEGDSHx/ZqhEZ2iMCgYEAk1RmOXDlDkiXeiNkzraxC7f07nZdsLFaXhl0Ls/98/Q26p6ckzwAMAgdRURG7gplwAJvrG7POn3tQ5iFTPkoJO/SUcuBPKhefaHTFbu7pDvr8W3WONWMX/kjLCNpp169Qw5hhwYLvDRn/MTAuelbRz1gCLXR++NVVeu10xe3nBsCgYBlGrT5b4/1tsz+rvZw7Uu673+fQEqTqveSGp4Cw9JPU8aj9IubKjMonnG6uB0Otraw7bjeM8CmXAqm/ZIi3S2NFhqsNq8xPXlQPqySB88Bx18UpksUX3jAnyUIAVep6NW317bRR0Nb42rgZiuVOwf6ruotuMvQnetREYs9UIt3AQKBgQDcy1+kVJicPX25VumzRQ+Zsk4ctjkcM3kXslLcA1+GkfKLj/PuYtVD4Dvsx3Bu17zvg+LAWI/QTBXwSPIz+k00ATDgnN6/FXH0qLW/5nS0HMMpEkOjJCpSMbXpTyOJic0WbO59+sC6HlJmcRMPK03uQEm6wt5foatp/aK4oxWzcw=="
  publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApssyH00FKvM3XYyQv9VdXIoTOdTxHarw+fx/w2uWvCWaK5Y7K9h8hc9HOEZcwgaolZ2M1+4ey+EEG77vtDaitqDC2+6ktScsoDQBn0zTT0H1GM4fEDpPhk7J6Cx998+trbRedkfU4eQYORMePnXIHdIEGhzUNRmbQNjnxhxGJEprXeG99B6NAKLPexhWNBO4m7SXpT9Oua33t1yRKm+urPMapCtp7q2dbqSb1UDRemM9EXup4U44NVBGeIhitNyEhcT55Yv8eteOz0dtEXJpKBpDZCmghLUJk9u3Duu7bH7dy4bcLBfoYWjukK5fG6K4W8l1bkPJrpPMJlZ3d5DP1wIDAQAB"
  notifyUrl: http://127.0.0.1:8081/pay/notify
  returnUrl: http://127.0.0.1:8081/#/order/list
